#ifndef EXCEPT_H
#define EXCEPT_H
#include <errno.h>

#define EXCEPTION errno

#define throw(ERROR_XXX, return_value) { errno = ERROR_XXX; return return_value; }
#define NO_VALUE

#define break_try  { errno = 0; break; }

#define try switch (errno)

#define catch case

#define catch_no_except case NO_ERROR: break_try;

#define end_try default: errno = 0; break

#define catch_except default

#define no_try errno = 0

#define return_except(return_value) { if (errno) { return return_value; } }

#define NO_ERROR 0
#define ERROR_OPERATION_NOT_PERMITTED 1
#define ERROR_NO_SUCH_FILE_OR_DIRECTORY 2
#define ERROR_NO_SUCH_PROCESS 3
#define ERROR_INTERRUPTED_FUNCTION_CALL 4
#define ERROR_INPUT_OUTPUT_ERROR 5
#define ERROR_NO_SUCH_DEVICE_OR_ADDRESS 6
#define ERROR_ARG_LIST_TOO_LONG 7
#define ERROR_EXEC_FORMAT_ERROR 8
#define ERROR_BAD_FILE_DESCRIPTOR 9
#define ERROR_NO_CHILD_PROCESSES 10
#define ERROR_RESOURCE_TEMPORARILY_UNAVAILABLE 11
#define ERROR_NOT_ENOUGH_SPACE 12
#define ERROR_PERMISSION_DENIED 13
#define ERROR_BAD_ADDRESS 14
#define ERROR_UNKNOWN_ERROR 15
#define ERROR_RESOURCE_DEVICE 16
#define ERROR_FILE_EXISTS 17
#define ERROR_IMPROPER_LINK 18
#define ERROR_NO_SUCH_DEVICE 19
#define ERROR_NOT_A_DIRECTORY 20
#define ERROR_IS_A_DIRECTORY 21
#define ERROR_INVALID_ARGUMENT 22
#define ERROR_TOO_MANY_OPEN_FILES_IN_SYSTEM 23
#define ERROR_TOO_MANY_OPEN_FILES 24
#define ERROR_INAPPROPRIATE_I_O_CONTROL_OPERATION 25
#define ERROR_FILE_TOO_LARGE 27
#define ERROR_NO_SPACE_LEFT_ON_DEVICE 28
#define ERROR_INVALID_SEEK 29
#define ERROR_READ_ONLY_FILE_SYSTEM 30
#define ERROR_TOO_MANY_LINKS 31
#define ERROR_BROKEN_PIPE 32
#define ERROR_DOMAIN_ERROR 33
#define ERROR_RESULT_TOO_LARGE 34
#define ERROR_RESOURCE_DEADLOCK_AVOIDED 36
#define ERROR_FILENAME_TOO_LONG 38
#define ERROR_NO_LOCKS_AVAILABLE 39
#define ERROR_FUNCTION_NOT_IMPLEMENTED 40
#define ERROR_DIRECTORY_NOT_EMPTY 41
#define ERROR_ILLEGAL_BYTE_SEQUENCE 42
#define ERROR_ADDRESS_IN_USE 100
#define ERROR_ADDRESS_NOT_AVAILABLE 101
#define ERROR_ADDRESS_FAMILY_NOT_SUPPORTED 102
#define ERROR_CONNECTION_ALREADY_IN_PROGRESS 103
#define ERROR_BAD_MESSAGE 104
#define ERROR_OPERATION_CANCELED 105
#define ERROR_CONNECTION_ABORTED 106
#define ERROR_CONNECTION_REFUSED 107
#define ERROR_CONNECTION_RESET 108
#define ERROR_DESTINATION_ADDRESS_REQUIRED 109
#define ERROR_HOST_UNREACHABLE 110
#define ERROR_IDENTIFIER_REMOVED 111
#define ERROR_OPERATION_IN_PROGRESS 112
#define ERROR_ALREADY_CONNECTED 113
#define ERROR_TOO_MANY_SYMBOLIC_LINK_LEVELS 114
#define ERROR_MESSAGE_SIZE 115
#define ERROR_NETWORK_DOWN 116
#define ERROR_NETWORK_RESET 117
#define ERROR_NETWORK_UNREACHABLE 118
#define ERROR_NO_BUFFER_SPACE 119
#define ERROR_NO_MESSAGE_AVAILABLE 120
#define ERROR_NO_LINK 121
#define ERROR_NO_MESSAGE 122
#define ERROR_NO_PROTOCOL_OPTION 123
#define ERROR_NO_STREAM_RESOURCES 124
#define ERROR_NOT_A_STREAM 125
#define ERROR_NOT_CONNECTED 126
#define ERROR_STATE_NOT_RECOVERABLE 127
#define ERROR_NOT_A_SOCKET 128
#define ERROR_NOT_SUPPORTED 129
#define ERROR_OPERATION_NOT_SUPPORTED 130
#define ERROR_VALUE_TOO_LARGE 132
#define ERROR_OWNER_DEAD 133
#define ERROR_PROTOCOL_ERROR 134
#define ERROR_PROTOCOL_NOT_SUPPORTED 135
#define ERROR_WRONG_PROTOCOL_TYPE 136
#define ERROR_STREAM_TIMEOUT 137
#define ERROR_TIMED_OUT 138
#define ERROR_TEXT_FILE_BUSY 139
#define ERROR_OPERATION_WOULD_BLOCK 140

#endif